#!/usr/bin/env bash
# setup-tmux-config.sh — Generate a well-documented .tmux.conf
set -euo pipefail

CONF="${HOME}/.tmux.conf"

if [[ -f "$CONF" ]]; then
    BACKUP="${CONF}.backup.$(date +%Y%m%d%H%M%S)"
    echo "Backing up existing config to ${BACKUP}"
    cp "$CONF" "$BACKUP"
fi

cat > "$CONF" << 'TMUXCONF'
# ===========================================================================
#  tmux configuration — generated by setup-tmux-config.sh
# ===========================================================================

# ---------------------------------------------------------------------------
#  General Settings
# ---------------------------------------------------------------------------

# Use C-a as prefix instead of C-b (easier to reach)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Enable 256-color and true-color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Increase scrollback buffer
set -g history-limit 50000

# Reduce escape-time for faster key response (important for vim/neovim)
set -sg escape-time 10

# Enable mouse support
set -g mouse on

# Enable focus events (useful for vim autoread)
set -g focus-events on

# ---------------------------------------------------------------------------
#  Key Bindings — Window Management
# ---------------------------------------------------------------------------

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Split panes with intuitive keys
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# New windows open in current path
bind c new-window -c "#{pane_current_path}"

# ---------------------------------------------------------------------------
#  Key Bindings — Pane Navigation
# ---------------------------------------------------------------------------

# Vim-style pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Alt+arrow pane switching (no prefix needed)
bind -n M-Left  select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up    select-pane -U
bind -n M-Down  select-pane -D

# ---------------------------------------------------------------------------
#  Key Bindings — Pane Resizing
# ---------------------------------------------------------------------------

# Resize panes with prefix + H/J/K/L
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ---------------------------------------------------------------------------
#  Key Bindings — Window Navigation
# ---------------------------------------------------------------------------

# Shift+arrow to switch windows (no prefix needed)
bind -n S-Left  previous-window
bind -n S-Right next-window

# Swap windows left/right
bind -r < swap-window -t -1\; select-window -t -1
bind -r > swap-window -t +1\; select-window -t +1

# ---------------------------------------------------------------------------
#  Copy Mode (vi-style)
# ---------------------------------------------------------------------------

setw -g mode-keys vi

# Enter copy mode with prefix + v
bind v copy-mode

# vi-style selection and yank
bind -T copy-mode-vi v   send-keys -X begin-selection
bind -T copy-mode-vi y   send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle

# Mouse selection copies to clipboard
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# ---------------------------------------------------------------------------
#  Status Bar
# ---------------------------------------------------------------------------

set -g status-position top
set -g status-interval 5

# Colors
set -g status-style "bg=#1e1e2e,fg=#cdd6f4"
set -g window-status-current-style "bg=#89b4fa,fg=#1e1e2e,bold"
set -g window-status-style "bg=#313244,fg=#a6adc8"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#89b4fa"
set -g message-style "bg=#89b4fa,fg=#1e1e2e"

# Left: session name
set -g status-left-length 30
set -g status-left "#[bg=#f38ba8,fg=#1e1e2e,bold] #S #[default] "

# Right: date and time
set -g status-right-length 50
set -g status-right "#[fg=#a6adc8] %a %b %d #[fg=#cdd6f4,bold]%H:%M "

# Window format
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-separator ""

# ---------------------------------------------------------------------------
#  Plugin Manager (TPM) — optional, install with setup-tpm.sh
# ---------------------------------------------------------------------------

# List of plugins (uncomment after installing TPM)
# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TPM (keep this at the very bottom)
# run '~/.tmux/plugins/tpm/tpm'
TMUXCONF

echo "Created ${CONF}"
echo "Reload in tmux with: prefix + r  (or: tmux source-file ~/.tmux.conf)"
